# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL", "redis://localhost:6379/3") %>
  channel_prefix: mmorpg_development

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL", "redis://localhost:6379/4") %>
  channel_prefix: mmorpg_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL", "redis://localhost:6379/5") %>
  channel_prefix: mmorpg_production
